version: '3.8'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: coderstew-website-app
    container_name: coderstew_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - /mnt/user/appdata/coderstew_website/composer:/var/www/html/.composer
    environment:
      APP_ENV: local
      APP_KEY: base64:someplaceholderkey
      DB_HOST: db
      DB_DATABASE: coderstew
      DB_USERNAME: coderstew
      DB_PASSWORD: password
      COMPOSER_HOME: /var/www/html/.composer
      COMPOSER_CACHE_DIR: /var/www/html/.composer/cache
    ports:
      - "9000:9000"

  web:
    image: nginx:alpine
    container_name: coderstew_web
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "8080:80"

  db:
    image: mysql:8
    container_name: coderstew_db
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/coderstew_website/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coderstew
      MYSQL_USER: coderstew
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

